//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjRoubado
    {
        public int IdObjRoubados { get; set; }
        public Nullable<bool> Dinheiro { get; set; }
        public Nullable<bool> Carteira { get; set; }
        public Nullable<bool> Documentos { get; set; }
        public Nullable<bool> Celular { get; set; }
        public Nullable<bool> Notebook { get; set; }
        public Nullable<bool> Motocicleta { get; set; }
        public Nullable<bool> Veiculo { get; set; }
        public Nullable<bool> OutrosEletronicos { get; set; }
        public Nullable<bool> Outros { get; set; }
        public int DenunciaIdDenuncia { get; set; }
    
        public virtual Denuncia Denuncia { get; set; }
    }
}
