//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.FaleConosco = new HashSet<FaleConosco>();
        }
    
        public int IdUsuario { get; set; }
        public string NomeCompleto { get; set; }
        public System.DateTime DtNasc { get; set; }
        public Nullable<bool> Experiencia { get; set; }
        public string Cidade { get; set; }
        public string Descricao { get; set; }
        public string User { get; set; }
        public short Senha { get; set; }
        public int CidadeIdCidade { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaleConosco> FaleConosco { get; set; }
        public virtual Denuncia Denuncia { get; set; }
    }
}
